Repository UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon, pull requests merged in 2023-10, with the labels that each got.

#96 Remove membro repetido do carrossel
  docs/index.html
Labels: bug, documentation

#92 80 docs diagrama de pacotes
  docs/Modelagem/Tradicional/Estaticos/DiagramaDePacotes.md
  docs/Modelagem/Tradicional/Estaticos/DiagramaDePacotesV1.png
  docs/Modelagem/Tradicional/Estaticos/DiagramaDePacotesV2.png
  docs/Modelagem/Tradicional/Estaticos/DiagramaDePacotesV3.png
  docs/Modelagem/Tradicional/Estaticos/DiagramaDePacotesVF.png
Labels: documentation

#90 81 docs diagrama de componentes
  docs/Modelagem/DiagramaDeComponentes/DiagramaDeComponentes.md
  docs/Modelagem/DiagramaDeComponentes/v1.png
  docs/Modelagem/DiagramaDeComponentes/v2.png
  docs/Modelagem/DiagramaDeComponentes/v3.png
Labels: documentation

#106 83 docs diagrama de implantação
  docs/Modelagem/Tradicional/Estatico/DiagramaDeImplantacao.md
  docs/Modelagem/Tradicional/Estatico/DiagramaDeImplantacao.png
Labels: documentation

#103 79 docs diagrama de sequência
  docs/Modelagem/DiagramaDeSequencia/DiagramaDeSequencia.md
  docs/Modelagem/DiagramaDeSequencia/DiagramaDeSequencia.png
Labels: documentation

#112 (#84) arrumando pasta e finalizando documento
  docs/Modelagem/DiagramaDeEstados/EstadosCadastro.png
  docs/Modelagem/DiagramaDeEstados/EstadosLoginV1.png
  docs/Modelagem/DiagramaDeEstados/EstadosProdV1.png
  docs/Modelagem/DiagramaDeEstados/EstadosProdutoVF.png
  docs/Modelagem/DiagramaDeEstados/diagrama_de_estados.md
  docs/Modelagem/DiagramaDeEstados/estados_pagamento.png
  docs/Modelagem/DiagramaDeEstados/estados_pagamento_primeira.jpg
Labels: documentation, arquitetura

#108 Entrega 2 - Organizar Pages
  docs/Entregas/ApresentacaoSobreMetodologias/ApresentacaoDeGrupo.md
  docs/Entregas/ApresentacaoSobreMetodologias/SinteseDoConteudo.md
  docs/Entregas/ApresentacaoSobreMetodologias/SlidesDaApresentacao.md
  docs/Entregas/ApresentacaoSobreMetodologias/assets/major-milestone.png
  docs/Entregas/ApresentacaoSobreMetodologias/assets/whale.png
  docs/Entregas/ApresentacaoSobreMetodologias/index.md
  docs/Entregas/ApresentacaoSobreMetodologias/slides/1.png
  docs/Entregas/ApresentacaoSobreMetodologias/slides/10.png
  docs/Entregas/ApresentacaoSobreMetodologias/slides/11.png
  docs/Entregas/ApresentacaoSobreMetodologias/slides/12.png
  docs/Entregas/ApresentacaoSobreMetodologias/slides/13.png
  docs/Entregas/ApresentacaoSobreMetodologias/slides/2.png
  docs/Entregas/ApresentacaoSobreMetodologias/slides/3.png
  docs/Entregas/ApresentacaoSobreMetodologias/slides/4.png
  docs/Entregas/ApresentacaoSobreMetodologias/slides/5.png
  docs/Entregas/ApresentacaoSobreMetodologias/slides/6.png
  docs/Entregas/ApresentacaoSobreMetodologias/slides/7.png
  docs/Entregas/ApresentacaoSobreMetodologias/slides/8.png
  docs/Entregas/ApresentacaoSobreMetodologias/slides/9.png
  docs/Entregas/Dois/DiagramaDeAtividade/DiagramaDeAtividade.md
  docs/Entregas/Dois/DiagramaDeAtividade/assets/Atividade UML Cadastro.png
  docs/Entregas/Dois/DiagramaDeAtividade/assets/UML_Compras.png
  docs/Entregas/Dois/DiagramaDeAtividade/assets/UML_Gestao.png
  docs/Entregas/Dois/DiagramaDeClasses/Classe UML - Amazon.png
  docs/Entregas/Dois/DiagramaDeClasses/Classe UML - Amazon_v2.1.png
  docs/Entregas/Dois/DiagramaDeClasses/Classe UML - Amazon_v2.png
  docs/Entregas/Dois/DiagramaDeClasses/Classe UML_V2.png
  docs/Entregas/Dois/DiagramaDeClasses/DiagramaDeClasses.md
  docs/Entregas/Dois/DiagramaDeComponentes/DiagramaDeComponentes.md
  docs/Entregas/Dois/DiagramaDeComponentes/v1.png
  docs/Entregas/Dois/DiagramaDeComponentes/v2.png
  docs/Entregas/Dois/DiagramaDeComponentes/v3.png
  docs/Entregas/Dois/DiagramaDeComunicacaoColaboracao/DiagramaDeComunicacaoColaboracao.md
  docs/Entregas/Dois/DiagramaDeComunicacaoColaboracao/v1.png
  docs/Entregas/Dois/DiagramaDeEstados/DiagramaDeEstados.md
  docs/Entregas/Dois/DiagramaDeEstados/EstadosCadastro.png
  docs/Entregas/Dois/DiagramaDeEstados/EstadosLoginV1.png
  docs/Entregas/Dois/DiagramaDeEstados/EstadosProdV1.png
  docs/Entregas/Dois/DiagramaDeEstados/EstadosProdutoVF.png
  docs/Entregas/Dois/DiagramaDeEstados/estados_pagamento.png
  docs/Entregas/Dois/DiagramaDeEstados/estados_pagamento_primeira.jpg
  docs/Entregas/Dois/DiagramaDeImplantacao/DiagramaDeImplantacao.md
  docs/Entregas/Dois/DiagramaDeImplantacao/DiagramaDeImplantacao.png
  docs/Entregas/Dois/DiagramaDePacotes/DiagramaDePacotes.md
  docs/Entregas/Dois/DiagramaDePacotes/DiagramaDePacotesV1.png
  docs/Entregas/Dois/DiagramaDePacotes/DiagramaDePacotesV2.png
  docs/Entregas/Dois/DiagramaDePacotes/DiagramaDePacotesV3.png
  docs/Entregas/Dois/DiagramaDePacotes/DiagramaDePacotesVF.png
  docs/Entregas/Dois/DiagramaDeSequencia/DiagramaDeSequencia.md
  docs/Entregas/Dois/DiagramaDeSequencia/DiagramaDeSequencia.png
  docs/Entregas/Dois/Participacoes.md
  docs/Entregas/Dois/index.md
  docs/Entregas/Um/Backlog.md
  docs/Entregas/Um/Participacoes.md
  docs/Entregas/Um/index.md
  docs/Modelagem/2.2.ParticipacoesModelagem.md
  docs/cronograma.md
  mkdocs.yml
Labels: documentation
