Repository UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon, pull requests merged in 2023-09, with the labels that each got.

#21 Melhorar documento de apresentação do grupo
  docs/Base/ApresentacaoDeGrupo.md
Labels: documentation

#28 2 elicitacao
  docs/Base/Engenharia-de-Requisitos/Eliticacao/Entrevista.md
  docs/assets/Piramide.PNG
Labels: bug, documentation, requisitos, repo

#34 33 docs eliminar arquivos duplicados
  CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/_sidebar.md
  docs/contribuindo.md
Labels: documentation, enhancement

#37 (#36) Update histórico de versão ata de reuniões
  docs/reunioes.md
Labels: documentation

#39 #38 - code of conduct email
  docs/CODE_OF_CONDUCT.md
Labels: documentation

#46 24 docs realizar a construção do protótipo
  docs/Base/4.0Prototipo.md
  docs/assets/prototipo/cadastro.png
  docs/assets/prototipo/compra_feita.png
  docs/assets/prototipo/confirmacao_do_pedido.png
  docs/assets/prototipo/forma_pagamento.png
  docs/assets/prototipo/home.png
  docs/assets/prototipo/lista_desejo.png
  docs/assets/prototipo/login.png
  docs/assets/prototipo/pesquisa.png
  docs/assets/prototipo/selecao_pagamento.png
  docs/assets/prototipo/vizualizar_produtos.png
Labels: documentation, requisitos, repo

#49 29 docs documento de entrega
  docs/Base/3.0 Participações.md
Labels: documentation

#51 (#50) Atualizando Cronograma
  docs/Base/cronograma.md
Labels: documentation

#53 48 docs backlog
  docs/Base/Engenharia-de-Requisitos/Modelagem/Backlog.md
  docs/Base/Engenharia-de-Requisitos/Priorização/TLE.md
Labels: documentation

#54 Atualizando Branch
  CODE_OF_CONDUCT.md
  docs/Base/2.0.Design_Sprint.md
  docs/Base/3.0 Participações.md
  docs/Base/4.0Prototipo.md
  docs/Base/BPMN.md
  docs/Base/Engenharia-de-Requisitos/Elicitação/5W2H.md
  docs/Base/Engenharia-de-Requisitos/Elicitação/Brainstorm.md
  docs/Base/Engenharia-de-Requisitos/Elicitação/Entrevista.md
  docs/Base/Engenharia-de-Requisitos/Elicitação/MapaMental.md
  docs/Base/Engenharia-de-Requisitos/Elicitação/RichPicture.md
  docs/Base/Engenharia-de-Requisitos/Elicitação/StoryBoard.md
  docs/Base/Engenharia-de-Requisitos/Modelagem/Backlog.md
  docs/Base/Engenharia-de-Requisitos/Modelagem/Léxicos.md
  docs/Base/Engenharia-de-Requisitos/Priorização/TLE.md
  docs/Base/Plano_de_risco.md
  docs/Base/cronograma.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/assets/BPMN_Metodologia.png
  docs/assets/BPMN_buy.png
  docs/assets/BPMN_cadastro.png
  docs/assets/MM - mão.jpg
  docs/assets/MapaMental.png
  docs/assets/Piramide.PNG
  docs/assets/RP_mylena_amazon_comprador.jpg
  docs/assets/RichPicture-Kauã.png
  docs/assets/amazon_riscos.png
  docs/assets/prototipo/cadastro.png
  docs/assets/prototipo/compra_feita.png
  docs/assets/prototipo/confirmacao_do_pedido.png
  docs/assets/prototipo/forma_pagamento.png
  docs/assets/prototipo/home.png
  docs/assets/prototipo/lista_desejo.png
  docs/assets/prototipo/login.png
  docs/assets/prototipo/pesquisa.png
  docs/assets/prototipo/selecao_pagamento.png
  docs/assets/prototipo/vizualizar_produtos.png
  docs/assets/rich-picture-AnaB.jpeg
  docs/assets/rich-picture-BeatrizVieira.jpeg
  docs/assets/rich-picture-Bruno.jpeg
  docs/assets/rich-picture-Guilherme.png
  docs/assets/rich-picture-Samuel.jpg
  docs/assets/rich-picture-arthur.jpeg
  docs/assets/rich-picture-gabriel.png
  docs/assets/rich_picture_AugustoDCamargo.jpg
  docs/contribuindo.md
  docs/reunioes.md
Labels: documentation

#57 (#56) Corrige workflow
  .github/workflows/mkdocs-deploy.yml
Labels: bug

#68 65 docs ajustar cronograma
  docs/Entregas/Um/Participacoes.md
  docs/cronograma.md
  mkdocs.yml
Labels: documentation, pendência

#71 63 docs metodologias e ferramentas utilizadas e fase de teste do design sprint
  docs/Entregas/Um/DesignSprint.md
  docs/Entregas/Um/Entrevista.md
  docs/Entregas/Um/EntrevistaValidacao.md
  docs/Entregas/Um/Prototipo.md
  docs/Entregas/Um/assets/ferramentas/bizagi_logo.png
  docs/Entregas/Um/assets/ferramentas/canva_logo.png
  docs/Entregas/Um/assets/ferramentas/discord_icon.png
  docs/Entregas/Um/assets/ferramentas/figma_logo.png
  docs/Entregas/Um/assets/ferramentas/github_logo.png
  docs/Entregas/Um/assets/ferramentas/kanban.png
  docs/Entregas/Um/assets/ferramentas/lucidchart.png
  docs/Entregas/Um/assets/ferramentas/vscode_logo.png
  docs/Entregas/Um/assets/ferramentas/whatsapp_logo.png
  docs/Entregas/Um/assets/prototipo/visualizar_produtos.png
  mkdocs.yml
Labels: documentation, pendência

#72 70 docs ajustar bpmn
  docs/Entregas/Um/BPMN.md
  docs/Entregas/Um/assets/BPMN_Metodologia.png
Labels: documentation, pendência

#73 Altera estrutura do git pages
  mkdocs.yml
Labels: documentation
